version: "3.12"

services:
  redis:
    container_name: redis1
    image: redis
    restart: always
    ports:
    - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend1
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - static_volume:/app/static
      - media_volume:/app/media

    expose:
      - "8000"
    environment:
      - SECRET_KEY=django-insecure-t&ic@4_=1io+sx41oq@j!5d^2juu^d04d&6dw%i0d^w3@t7rb+
      - DEBUG=False
    depends_on:
      - redis
  
  nginx:
    image: nginx
    container_name: nginx1
    restart: always
    ports: 
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - redis
      - backend


volumes:
  static_volume:
  media_volume: